// Konfigurasi chain multi-EVM untuk Kavach Wallet — Phase 1
// Semua RPC adalah endpoint publik gratis. Standar BIP-44 coin type 60 = seluruh EVM.

export const CHAINS = [
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    chainId: 1,
    rpc: 'https://eth.llamarpc.com',
    explorer: 'https://etherscan.io',
    coinGeckoId: 'ethereum',
    color: '#627EEA',
    gradient: 'from-indigo-500 to-blue-600',
    logoText: 'ETH',
  },
  {
    id: 'bsc',
    name: 'BNB Smart Chain',
    symbol: 'BNB',
    chainId: 56,
    rpc: 'https://bsc-dataseed.binance.org',
    explorer: 'https://bscscan.com',
    coinGeckoId: 'binancecoin',
    color: '#F0B90B',
    gradient: 'from-yellow-400 to-amber-500',
    logoText: 'BNB',
  },
  {
    id: 'polygon',
    name: 'Polygon',
    symbol: 'POL',
    chainId: 137,
    rpc: 'https://polygon-rpc.com',
    explorer: 'https://polygonscan.com',
    coinGeckoId: 'matic-network',
    color: '#8247E5',
    gradient: 'from-purple-500 to-violet-600',
    logoText: 'POL',
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum One',
    symbol: 'ETH',
    chainId: 42161,
    rpc: 'https://arb1.arbitrum.io/rpc',
    explorer: 'https://arbiscan.io',
    coinGeckoId: 'ethereum',
    color: '#28A0F0',
    gradient: 'from-sky-500 to-cyan-500',
    logoText: 'ARB',
  },
  {
    id: 'optimism',
    name: 'Optimism',
    symbol: 'ETH',
    chainId: 10,
    rpc: 'https://mainnet.optimism.io',
    explorer: 'https://optimistic.etherscan.io',
    coinGeckoId: 'ethereum',
    color: '#FF0420',
    gradient: 'from-red-500 to-rose-600',
    logoText: 'OP',
  },
  {
    id: 'base',
    name: 'Base',
    symbol: 'ETH',
    chainId: 8453,
    rpc: 'https://mainnet.base.org',
    explorer: 'https://basescan.org',
    coinGeckoId: 'ethereum',
    color: '#0052FF',
    gradient: 'from-blue-600 to-indigo-700',
    logoText: 'BASE',
  },
];

export const getChain = (id) => CHAINS.find((c) => c.id === id);
