kind = "web"
previewPath = "/"
title = "Cavendish Wallet"
version = "1.0.0"
id = "artifacts/kavach-wallet"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24009

[services.development]
run = "pnpm --filter @workspace/kavach-wallet run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kavach-wallet", "run", "build" ]
serve = "static"
publicDir = "artifacts/kavach-wallet/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24009"
BASE_PATH = "/"
