// Konfigurasi 10 chain untuk Kavach Wallet
// Family: 'evm' | 'btc' | 'sol' | 'trx'

export const CHAINS = [
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    family: 'evm',
    chainId: 1,
    rpc: 'https://eth.llamarpc.com',
    explorer: 'https://etherscan.io',
    txPath: '/tx/',
    coinGeckoId: 'ethereum',
    decimals: 18,
    gradient: 'from-indigo-500 to-blue-600',
    logoText: 'ETH',
    lifiChainId: 1,
    nativeAddress: '0x0000000000000000000000000000000000000000',
    canSend: true,
    canSwap: true,
  },
  {
    id: 'bsc',
    name: 'BNB Smart Chain',
    symbol: 'BNB',
    family: 'evm',
    chainId: 56,
    rpc: 'https://bsc-dataseed.binance.org',
    explorer: 'https://bscscan.com',
    txPath: '/tx/',
    coinGeckoId: 'binancecoin',
    decimals: 18,
    gradient: 'from-yellow-400 to-amber-500',
    logoText: 'BNB',
    lifiChainId: 56,
    nativeAddress: '0x0000000000000000000000000000000000000000',
    canSend: true,
    canSwap: true,
  },
  {
    id: 'polygon',
    name: 'Polygon',
    symbol: 'POL',
    family: 'evm',
    chainId: 137,
    rpc: 'https://polygon-rpc.com',
    explorer: 'https://polygonscan.com',
    txPath: '/tx/',
    coinGeckoId: 'matic-network',
    decimals: 18,
    gradient: 'from-purple-500 to-violet-600',
    logoText: 'POL',
    lifiChainId: 137,
    nativeAddress: '0x0000000000000000000000000000000000000000',
    canSend: true,
    canSwap: true,
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum One',
    symbol: 'ETH',
    family: 'evm',
    chainId: 42161,
    rpc: 'https://arb1.arbitrum.io/rpc',
    explorer: 'https://arbiscan.io',
    txPath: '/tx/',
    coinGeckoId: 'ethereum',
    decimals: 18,
    gradient: 'from-sky-500 to-cyan-500',
    logoText: 'ARB',
    lifiChainId: 42161,
    nativeAddress: '0x0000000000000000000000000000000000000000',
    canSend: true,
    canSwap: true,
  },
  {
    id: 'optimism',
    name: 'Optimism',
    symbol: 'ETH',
    family: 'evm',
    chainId: 10,
    rpc: 'https://mainnet.optimism.io',
    explorer: 'https://optimistic.etherscan.io',
    txPath: '/tx/',
    coinGeckoId: 'ethereum',
    decimals: 18,
    gradient: 'from-red-500 to-rose-600',
    logoText: 'OP',
    lifiChainId: 10,
    nativeAddress: '0x0000000000000000000000000000000000000000',
    canSend: true,
    canSwap: true,
  },
  {
    id: 'base',
    name: 'Base',
    symbol: 'ETH',
    family: 'evm',
    chainId: 8453,
    rpc: 'https://mainnet.base.org',
    explorer: 'https://basescan.org',
    txPath: '/tx/',
    coinGeckoId: 'ethereum',
    decimals: 18,
    gradient: 'from-blue-600 to-indigo-700',
    logoText: 'BASE',
    lifiChainId: 8453,
    nativeAddress: '0x0000000000000000000000000000000000000000',
    canSend: true,
    canSwap: true,
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    symbol: 'AVAX',
    family: 'evm',
    chainId: 43114,
    rpc: 'https://api.avax.network/ext/bc/C/rpc',
    explorer: 'https://snowtrace.io',
    txPath: '/tx/',
    coinGeckoId: 'avalanche-2',
    decimals: 18,
    gradient: 'from-red-600 to-pink-600',
    logoText: 'AVAX',
    lifiChainId: 43114,
    nativeAddress: '0x0000000000000000000000000000000000000000',
    canSend: true,
    canSwap: true,
  },
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    family: 'btc',
    explorer: 'https://mempool.space',
    txPath: '/tx/',
    coinGeckoId: 'bitcoin',
    decimals: 8,
    gradient: 'from-orange-500 to-amber-600',
    logoText: 'BTC',
    canSend: false,
    canSwap: false,
  },
  {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    family: 'sol',
    rpc: 'https://api.mainnet-beta.solana.com',
    explorer: 'https://solscan.io',
    txPath: '/tx/',
    coinGeckoId: 'solana',
    decimals: 9,
    gradient: 'from-purple-600 to-fuchsia-500',
    logoText: 'SOL',
    canSend: true,
    canSwap: false,
  },
  {
    id: 'tron',
    name: 'Tron',
    symbol: 'TRX',
    family: 'trx',
    explorer: 'https://tronscan.org',
    txPath: '/#/transaction/',
    coinGeckoId: 'tron',
    decimals: 6,
    gradient: 'from-rose-500 to-red-700',
    logoText: 'TRX',
    canSend: false,
    canSwap: false,
  },
];

export const getChain = (id) => CHAINS.find((c) => c.id === id);

export const EVM_CHAINS = CHAINS.filter((c) => c.family === 'evm');
